# Generated by Django 4.2.4 on 2025-07-02 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='value', max_length=50, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('value_text', models.TextField(blank=True, max_length=200, null=True)),
                ('item_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
    ]
